name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: shiftrx
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install testing dependencies
        run: pip install pytest

      - name: Wait for Postgres to be ready
        run: |
          for i in {1..10}; do
            if nc -z localhost 5432; then
              echo "Postgres is ready"
              break
            else
              echo "Waiting for Postgres..."
              sleep 5
            fi
          done

      - name: Run tests
        env:
          OPENAI_API_KEY: dummy-key
        run: pytest
